# SQLite version 3.x
#   gem install sqlite3
development:
  adapter: postgresql
  encoding: unicode
  host: tesis.ana
  database: wedraw
  pool: 5
  username: postgres
  password: lap

production:
  url: <%= ENV['DATABASE_URL'] %>
